"""
Real-time streaming TTS using ElevenLabs WebSocket API
Streams audio chunks as they're generated - INSTANT audio delivery
"""

import logging
import os
from elevenlabs.client import ElevenLabs

logger = logging.getLogger(__name__)


class RealtimeStreamingService:
    """
    Handle real-time TTS streaming with ElevenLabs
    - Stream audio chunks instantly as generated (no waiting for full audio)
    - Perfect for live applications
    """
    
    def __init__(self):
        self.api_key = os.environ.get('ELEVENLABS_API_KEY')
        self.client = ElevenLabs(api_key=self.api_key)
    
    def stream_text_to_speech(self, text, voice_id='21m00Tcm4TlvDq8ikWAM', model_id='eleven_multilingual_v2'):
        """
        Stream TTS audio chunks INSTANTLY (not wait for full audio)
        
        Args:
            text: Text to convert
            voice_id: ElevenLabs voice ID
            model_id: Model to use (v2 supports multilingual)
            
        Yields:
            bytes: Audio chunks as they're generated by ElevenLabs
        """
        try:
            # ElevenLabs streaming - returns chunks immediately
            audio_stream = self.client.text_to_speech.stream(
                text=text,
                voice_id=voice_id,
                model_id=model_id
            )
            
            for chunk in audio_stream:
                if isinstance(chunk, bytes) and chunk:
                    yield chunk
                    
        except Exception as e:
            logger.error(f"Streaming TTS error: {str(e)}")

